# Setup
title:               "Jumanji144's Blog"
tagline:             'Java and C++ developer'
description:         'I post blogs featuring tutorials on jvm internals and some other things'
url:                 https://jumanji144.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Justus Garbe
  url:               https://twitter.com/jumanji1444
  email:             justus.elias.garbe@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
