# Setup
title:               "Jumanji144's Blog"
tagline:             'Java and C++ developer'
description:         'I post blogs featuring tutorials on jvm internals and some other things'
url:                 https://jumanji144.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Justus Garbe
  url:               https://twitter.com/jumanji1444
  email:             justus.elias.garbe@gmail.com

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.2.0
google_analytics_id: #UA-XXXX-Y
